name: Publish Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - uses: actions/setup-node@v3
      - run: npm ci --no-audit
      - run: npm run build
